name: Test GH Action

on:
  push:
    branches:
      - main

# env: 
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Group test
        uses: Pandoriux/zephyr-release@test
        with:
          config-path: ./zephyr-release-config.json
          config-override: |
            {
              "name": "override"
            }