name: Test GH Action

on:
  push:
    branches:
      - main

# env: 
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Group test
        run: |
          echo "::group::Quick test:"
          echo "inside group"
          echo "::endgroup::"

      - name: Group test 2
        run: |
          echo "::group::Quick tests"
          echo "inside group"
          echo "::endgroup::"